### ISSUE TITLE
dataset not available 

### ISSUE THREAD

**Issue by raycarter** [acdh-oeaw/ACDHhackathonELEXIS#1]
When I open the link https://id.acdh.oeaw.ac.at/uuid/175b8cdf-5d04-f4d3-a778-67910aa8fd37 to download the dataset, it shows me "Not Found". Maybe the link in the README is wrong. Thanks if you could take a look at it.

**Comment by vanyh** [comment]
Thank you for the remark - due to a security update, our servers are currently under maintenance. That's bad timing - we apologize for the inconvenience and will let you know as soon as we are back online.

**Comment by raycarter** [comment]
It seems the servers are back online. I'm closing this issue. Thanks!
